### ISSUE TITLE
Synchronization between local and CKAN datasets

### ISSUE THREAD

**Issue by gabrielbdornas** [transparencia-mg/dpckan#105]
### What

Use the dpckan package to intelligently update a dataset published to CKAN from your local copy. Currently, the package is able to update resources of a set in CKAN, being necessary to do so, during the call of the CLI function `dpckan resource update`, inform which resource will be updated. Therefore, the package is not able to compare the local resources with those existing in the desired CKAN instance to determine which ones are different and therefore need to be updated.

## Why

This functionality proved to be important given the size that some sets can reach, both in number of resources and in disk space, over time. In this sense, a process that simply updates all the resources of a given set, regardless of whether it has changed or not, may prove to be inefficient or even unfeasible.

### How

- Creating a `dpckan pull` routine to "read" the resources existing in the desired CKAN instance;
- Comparing any changes and synchronizing the two environments; and
- Updating `dpckan dataset update` command to update in CKAN only locally modified resources after `dpckan pull`.

## User Story:

- As a publisher/update of datasets in CKAN instances;
- I want dpckan to compare remote resources with local ones, allowing resource updates only with some modification;
- So that I can:
  - Use the `dpckan dataset pull` command to synchronize the most up-to-date information available on the desired CKAN instance with the local repository (similar process to the `git pull` command from the git version control tool. Note: CKAN API endpoints like [package_show](https://docs.ckan.org/en/2.9/api/#ckan.logic.action.get.package_show) could be used in this creation.
- Use `dpckan dataset compare` command to compare all the files synchronized in the previous command with the modifications that were eventually made. Note: Resources such as `git status > log.txt` can be used to record the log with the modified files. It is noteworthy that this command will be used after making the necessary local modifications to the set, such as updating the data, validating the new data from the metadata, adjusting the new data or metadata from the responses received during the validation process, etc.
- Use `dpckan dataset update` command to update in the desired CKAN instance only resources that have undergone some modification/inclusion/exclusion.

### O que

Utilizar o pacote dpckan para atualizar de maneira inteligente um conjunto de dados publicado no CKAN a partir de sua cópia local. Atualmente, o pacote é capaz de atualizar recursos de um conjunto no CKAN sendo necessário para tal, durante a chamada da função CLI [`dpckan resource update`](https://github.com/dados-mg/dpckan#atualiza%C3%A7%C3%A3o-de-recurso-via-terminal), informar qual recurso será atualizado. Sendo assim, o pacote não é capaz de comparar os recursos locais com os existentes na instância do CKAN desejada para determinar quais são diferentes e portanto necessários de atualização. 

## Porque

Essa funcionalidade mostrou-se importante visto o tamanho que alguns conjuntos podem atingir, tanto em número de recursos quanto em espaço em disco, ao longo do tempo. Neste sentido, pensar em um processo que simplesmente atualiza todos os recursos de determinado conjunto, independente de este ter sofrido alteração ou não, pode se mostrar ineficiente ou até mesmo inviável.

### Como 

- Criando uma rotina `dpckan pull` para "ler" os recursos existentes na instância do CKAN desejada; 
- Comparando eventuais modificações e sincronizando os dois ambientes; e
- Atualizando o comando `dpckan dataset update` para atualizar no CKAN apenas recursos modificados localmente após o `dpckan pull`.

## História de usuário:

- Como um publicador/atualizador de conjuntos de dados em intâncias do CKAN;
- Eu quero que o dpckan compare os recursos remotos com os locais, permitindo apenas atualização de recursos com alguma modificação;
- De maneira que eu possa:
  - Utilizar o comando `dpckan dataset pull` para sincronizar as informações mais atualizadas disponíveis na instância do CKAN desejada com o repositório local (processo similar ao comando `git pull` da ferramenta de controle de versão git. Obs.: Podendo end-points como [package_show](https://docs.ckan.org/en/2.9/api/#ckan.logic.action.get.package_show) serem utilizados nesta criação.
- Utilizar comando `dpckan dataset compare` para comparar todos os arquivos sincronizados no comando anterior com as modificações eventuamente realizadas. Obs.: Podendo recursos como `git status > log.txt` serem utilizados para registro do log com os arquivos modificados. Vale ressaltar que este comando será utilizado após a realização de modificações locais necessárias no conjunto, tais como atualização dos dados, validação dos novos dados a partir dos metadados, ajuste nos novos dados ou metadados a partir das respostas recebidas durante processo de validação, etc.
- Utilizar comando `dpckan dataset update` para atualizar na instância do CKAN desejada apenas recursos que sofreram alguma modificação/inclusão/exclusão.

**Comment by gabrielbdornas** [comment]
## Ideia de implementação

Em linhas gerais, acredito que o macroprocesso abaixo poderia ser implementado:

- Utilizar o [endpoint package_show](https://docs.ckan.org/en/2.9/api/#ckan.logic.action.get.package_show) para listar todos os recursos de determinado pacote;
- O json retornado na etapa acima contém um array com todos informações dos recursos como id e link de referência;
- Implementar uma processo para verificar o ckecksum de todos os recursos listados no json, similar ao sugerido [aqui](https://gist.github.com/neonprimetime/10700a1a8ac41942ed56), ou:

```
from urllib.request import urlopen
import os, hashlib, optparse

def get_remote_md5_sum(url):
  remote = urlopen(url)
  return hash(remote)

def hash(remote, algorithm="md5"):
  max_file_size=100*1024*1024
  hash = hashlib.md5()
  total_read = 0
  while True:
    data = remote.read(4096)
    total_read += 4096
    if not data or total_read > max_file_size:
      break
    hash.update(data)
  return hash.hexdigest()
```
- Conforme demostrado no issue #107 não há como utilizar a tag "name" do json retornando no endpoint da api pela posibilidade de mesmos valores para recursos diferentes. Sendo assim necessário seria incluir nas funções `dpckan dataset create` ou `dpckan resource create` um processo que atualizaria o resource dentro do datapackage.json com um objeto que guardaria para cada host seu respectivo id. Feito isso a comparação da hash do arquivo local com remoto será possível implementar. Abaixo exemplo de objeto a ser incluído em cada recurso após criação do mesmo na instância do CKAN desejada:

```
resources: [
{
...
ids: {
https://homologa.cge.mg.gov.br/: 8284cf6e-5b29-43e3-967a-7bf098d590cf,
https://dados.mg.gov.br/: 3569cf6e-5b29-43e3-967a-7bf098d591çp
}
}

]
```
- Criar uma pasta .dpckan para armazenar o json retornado no endpoint atualizado com as hashs de todos os recursos. Observar o issue #118. 
- Utilizar timestamp no padrão do nome do json a ser salvo no item anterior
- Deixar somente o último arquivo na pasta .dpckan
- Incluir a pasta .dpckan no .gitignore do conjunto (incluir esta observação na documentação do pacote). 
- Implementar comando `dpckan dataset pull`:

```
for ckan_ressources in ckan_ressource:
  se checksum do ckan_ressource for igual ao ckecksum do local_resource
      mantem arquivo
  se checksum do ckan_ressource for diferente ao ckecksum do local_resource
      atualiza arquivo local, baixando o arquivo do ckan
  id do ckan_ressource não existir no local_resource
      cria arquivo local, baixando o arquivo do ckan
  id local_resource não existir no ckan_ressource
      exclui local_resource
```
- Obs.: Comando `dpckan dataset smart-update` somente poderá ser acionado caso o ckecksum do arquivo armazenado na pasta .dpckan seja igual à consulta na mesma api no momento anterior à atualização. Isso garantirá que o repositório local está sincronizado com o remoto e que nenhuma modificação no remoto foi realizada no intervalo entre o comando `dpckan dataset pull`, as eventuais modificações/atualização local e seu envio para o repositório remoto. Caso não haja pasta .dpckan ou até mesmo nenhum arquivo dentro da mesma processo também deverá ser abortado.

- Implementar comando `dpckan dataset smart-update`:

```
for local_resources in local_resource:
  se checksum do local_resource for igual ao ckan_ressource
      mantem arquivo
  se checksum do ckan_ressource for diferente ao ckecksum do ckan_ressource
      atualiza arquivo do ckan
  id do ckan_local não existir no ckan_resource
      cria arquivo no ckan
  id ckan_ressource não existir no local_resource
      exclui ckan_resource

atualiza informações conjunto lendo datapackage.json se alguma modificação acima tenha sido realizada
```

- Obs.: Função `dpckan delete resource` deverá ser criada para excluir recurso não existente no local

- json criado durante `dpckan dataset smart-update` deverá ser excluído devendo o log de toda operação ser registrada para controle futuro

## Premissas

- Conjunto de dados publicado na instância do CKAN será considerado como um repositório online (principal) do conjunto, nos moldes de um repositório github. Sendo assim o fluxo de trabalho de atualização do recuso envolverá:
    - Criação de um branch a partir da main para início da atualização do conjunto de dados;
    - `dpckan dataset pull`: para compar todos os recursos existentes no CKAN com o local, sendo modificado o local caso alguma diferença seja encontrada;
    - Comitar eventuais modificações realizadas localmente após `dpckan dataset pull`;
    - Atualização dos dados;
    - Validação dos dados a partir dos metadados;
    - Correções metadados (caso necessária);
    - Comitar atualizações;
    - `dpckan dataset smart-update` para atualizar apenas arquivos modificados. Arquivo somente poderá ser acionado se log do último `dpckan dataset pull` mostrar igualdade entre repositórios remoto e local

- Processo permitirá trabalhos tanto na linha de comando quanto na aplicação CKAN

- Processos `dpckan dataset create` ou `dpckan resource create` atualizando datapackage.json com id dos recursos criados. @fjuniorr havia comentado que não gostava muito desta ideia por considerar a modificação no padrão do datapackage.json e esta não se aplicar para todos os processos. Uma possibilidade seria criar a validação para não publicação de recurso com mesma tag "title" para utilizar o "name" do json retornado na API, além de deixar claro esta obrigatoriedade na documentação, mas particularmente não gosto muito desta possibilidade.

**Comment by gabrielbdornas** [comment]
@fjuniorr, primeira versão da sincronização realizada [neste commit](https://github.com/dados-mg/dpckan/tree/4487d2888efdba6b3aa71963dd0ed2dfcab77e29)

**Comment by fjuniorr** [comment]
@gabrielbdornas acho que temos um problema conceitual nessa implementação para o caso de uso do https://github.com/transparencia-mg/age7. 

Lá, o arquivo `datapackage.json` é considerado um artefato descartável do processo de build, sendo literalmente um target do `Makefile`: 

```bash
datapackage.json: scripts/python/build-datapackage.py datapackage.yaml schemas/* data/* logs/validate/* dialect.json README.md CHANGELOG.md CONTRIBUTING.md
	python $<
```

Isso significa que os metadados armazenados no `datapackage.json`, incluindo o `ckan_hosts`, são removidos depois da execução de um `make datapackage.json`. Seguindo essa lógica, a inserção do `ckan_hosts` pelo `dpckan dataset create` deveria ser no `datapackage.yaml`, e não no `datapackage.json`.

No entanto, a serialização como `yaml` não faz parte da especificação frictionless, pelo menos ainda, e representa um caso de uso específico. Não seria interessante que a gente dependesse desse escolha para que o usuário pudesse usar o `dpckan dataset update`.

Além disso, refletindo um pouco mais acho que no fim das contas não é uma boa ideia a gente modificar, ainda mais sem nenhum tipo de aviso ao usuário, o `datapackage.json` local.

Imagina por exemplo um cenário em que o usuário não está versionando o arquivo `datapackage.json` e o `dpckan` esteja com alguma falha que modifica e/ou destroi o conteúdo do arquivo. A confiança vai a zero.

Penso que a melhor alternativa vai ser a gente armazenar o `ckan_hosts` somente na propriedade `extras` do conjunto de dados no CKAN.

**Comment by gabrielbdornas** [comment]
@fjuniorr, considero que este issue pode ser fechado depois da publicação [da versão v.0.1.11](https://github.com/dados-mg/dpckan/tree/9f1e4bb53ebf95cabf5b8a835ba46854e5aef4f4). O que você acha de colocarmos seu [útlimo comentário](https://github.com/dados-mg/dpckan/issues/105#issuecomment-978411276), que eu concordo, em um issue próprio?

**Comment by fjuniorr** [comment]
Concordo. 

Novo issue criado https://github.com/dados-mg/dpckan/issues/140

**Comment by gabrielbdornas** [comment]
@fjuniorr, acredito que esquecemos de fechar este issue. Posso fechar?
