### ISSUE TITLE
Investigar API do CKAN

### ISSUE THREAD

**Issue by gabrielbdornas** [transparencia-mg/dpckan#108]
@mauriciocge gostaria de investigar porque a tag "hash" não vem preenchida no json de retorno do endpoint package_show da API do CKAN, conforme figura abaixo:

![image](https://user-images.githubusercontent.com/49699290/136105157-dc52963b-b753-4df6-8d77-2cf32005147c.png)

**Comment by gabrielbdornas** [comment]
@fjuniorr acha que vale abrir um chamado para a TI sobre este assunto? A ideia seria utilizar o próprio CKAN para gerar o checksum dos recursos do CKAN, no lugar da função abaixo:

https://github.com/transparencia-mg/dpckan/blob/bb0919034bb7ea5f47ffe97cd513c08b71423cb1/dpckan/functions.py#L211-L231

**Comment by fjuniorr** [comment]
É um tópico que vale a investigação sim, mas podemos começar com uma investigação nossa.

Você já fez um teste de enviar essa informação com [`resource_create`](http://docs.ckan.org/en/2.8/api/index.html#ckan.logic.action.create.resource_create) e ver se ela passa a ser retornada? Se a propriedade está vazia, tem cara de ser algo que é informado pelos usuários, e não calculado pelo CKAN.

**Comment by gabrielbdornas** [comment]
> É um tópico que vale a investigação sim, mas podemos começar com uma investigação nossa.
> 
> Você já fez um teste de enviar essa informação com [`resource_create`](http://docs.ckan.org/en/2.8/api/index.html#ckan.logic.action.create.resource_create) e ver se ela passa a ser retornada? Se a propriedade está vazia, tem cara de ser algo que é informado pelos usuários, e não calculado pelo CKAN.

@fjuniorr acertou!

A título de teste inclui um atributo hash durante o resource_create:

```
  resource_has = '123456'
  payload = {"package_id":datapackage_id,
               "name": resource.title,
               "description": resource.description,
               "url": resource.path,
               "hash": resource_has,}
```

Que retornou ou valor durante a chamada da API:

```
resources": [
      {
        "mimetype": "text/csv",
        "cache_url": null,
        "hash": "123456",
        "description": "This file contains the actual data with Letters consonants",
        "name": "Consonants",
        "format": "CSV",
```
