### ISSUE TITLE
Desenvolvimento `dpckan get`

### ISSUE THREAD

**Issue by fjuniorr** [transparencia-mg/dpckan#144]
Comando para fazer download de um conjunto de dados do CKAN como um data package local para permitir a utilização das demais ferramentas do ecossistema frictionless.

```
dpckan get <host/dataset> <dataset> <path>
```

**Comment by gabrielbdornas** [comment]
@fjuniorr, algumas observações sobre o desenvolvimento da funcionalidade, implementada [neste branch](https://github.com/dados-mg/dpckan/tree/include-get-function).

- Não mergiei o código porque gostaria de uma revisão sua, ainda que só da parte conceitual;
- Na abertura do issue você sugere criar o comando `dpckan get <host/dataset> <dataset> <path>`, mas preferi utilizar `dpckan dataset get` como forma de mantermos o padrão utilizado até o momento nas chamadas das funções do pacote;
- Neste mesmo sentido de manter o padrão, o host considerará como padrão a variável de ambiente CKAN_HOST, caso contrário o usuário deverá passar esta informação via `-H` flag;
- A estrutura criada foi a mais simples possível para esta primeira versão, sendo o arquivo datapackage.json salvo na raiz do diretório, ou aonde o comando for executado, e os demais arquivos dos recursos salvos na pasta data. Podemos aprimorar deixando o usuário escolher o caminho na qual os arquivos baixados serão salvos;
- Não criei uma pasta para salvar schemas pois esta informação encontra-se dentro do arquivo datapackage.json, mas podemos incluí-la como melhoria da funcionalidade;
- Tentei criar a documentação básia para esta funcionalidade, tanto no arquivo README.md quando no docstring que são utilizados para criação dos comandos CLI.

Sugestões de melhorias futuras (não implementadas para discutirmos melhor o que seria mais viável):
- Verificar a existência do conjunto desejado na instância do CKAN, evitando assim erro 'ckanapi.errors.NotAuthorized'. Já existe uma função que testa a existência do conjunto, mas ela recebe como parâmetro um datapackage. Seria necessário mudar esta função para que ela receba o nome;
- Criar uma pasta com nome do conjunto aonde arquivos serão salvos. Ou criação de flag para indicar aonde esta pasta deverá ser salva;
- Criação de pasta para armazenar shemas, ou flag dando esta opção;
- Dar opção de utilizar apenas a url do conjunto durante chamada da função. Isso evitaria ter que passar host e id do conjunto
