### ISSUE TITLE
Migrar repositório para organização transparência

### ISSUE THREAD

**Issue by gabrielbdornas** [transparencia-mg/dpckan#150]
@fjuniorr, podemos migrar o dpckan para https://github.com/transparencia-mg, para conseguirmos incluir os issues no nosso projeto @work?

**Comment by fjuniorr** [comment]
Estou bem convencido que vai fazer sentido pra gente mesclar as organizações pra otimizar o uso dos [projetos (beta)](https://docs.github.com/en/issues/trying-out-the-new-projects-experience/about-projects), então de fato vale a pena migrar.

Já fiz isso e os redirecionamentos (repo, issues, PRs) estão todos funcionando.

Lembrar de seguir essa recomendação da [documentação](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository) sobre transferências de repositórios

> All links to the previous repository location are automatically redirected to the new location. When you use git clone, git fetch, or git push on a transferred repository, these commands will redirect to the new repository location or URL. However, to avoid confusion, we strongly recommend updating any existing local clones to point to the new repository URL. You can do this by using git remote on the command line:
> 
> ```
> $ git remote set-url origin new_url
> ```
