### ISSUE TITLE
Implementar cobertura de testes de 30% do código

### ISSUE THREAD

**Issue by gabrielbdornas** [transparencia-mg/dpckan#166]
Seguir lista sugerida [aqui](https://github.com/transparencia-mg/dpckan/issues/164#issuecomment-1051084228).

**Comment by fjuniorr** [comment]
Vou trabalhar na configuração da cobertura de código no PR https://github.com/transparencia-mg/dpckan/pull/174. 

Ainda não fiz a configuração para apuração via [codecov](https://about.codecov.io/), mas para apuração local adicionei o target `make coverage`. No branch `dev` o relatório é

![20220317T172947](https://user-images.githubusercontent.com/4969445/158891221-3cc82d89-9388-401d-a575-e6d1289e89b6.png)
