### ISSUE TITLE
Create "related projects" section for README

### ISSUE THREAD

**Issue by fjuniorr** [transparencia-mg/dpckan#29]
### What

Create a "related projects" section in the `README.md` to help new users evaluate if `dpckan` fits their use case better than other tools in the broader Frictionless and CKAN ecosystem and understand where it is positioned in this space. In the words of [ROpenSci software review template](https://github.com/ropensci/software-review/blob/master/.github/ISSUE_TEMPLATE/A-submit-software-for-review.md) 

> Are there other ~R packages~ tools that accomplish the same thing? If so, how does yours differ or meet our [criteria for best-in-category](https://devguide.ropensci.org/policies.html#overlap)?

### Why

Understand where a tool fits and what gap it solves is hard and time consuming. We should to the extent possible make it easier for users to make sound decisions in this respect with the minimal effort.

Tools builders are uniquely positioned to do this and open source software from government should create the honest assessment as possible.

### How

The section should at least compare and contrast `dpckan` with the projects

- [ckanext-datapackager](https://github.com/frictionlessdata/ckanext-datapackager). CKAN extension for importing/exporting Data Packages
- [frictionless-py CKAN plugin](https://framework.frictionlessdata.io/docs/tutorials/formats/ckan-tutorial/)
- [datapackage-pipelines-ckan](https://github.com/frictionlessdata/datapackage-pipelines-ckan). Data Package Pipelines processors for CKAN

It should also explain the essential goal of remote data package synchronization (ie. incremental updates) and the architecture decision to have a tool that can be used with CKAN instances that are not necessarily under control of the `dpckan` user and/or has support for data packages.

Some links for inspiration here

- https://github.com/rstudio/gt#how-gt-fits-in-with-other-packages-that-generate-display-tables
- https://github.com/rich-iannone/pointblank#how-pointblank-fits-in-with-other-packages-that-validate-tabular-data
- https://github.com/junegunn/fzf/wiki/Related-projects
- https://github.com/BurntSushi/ripgrep#why-shouldnt-i-use-ripgrep
- https://click.palletsprojects.com/en/8.0.x/why/

## Portuguese version <a href="#user-content-portuguese-version" id="portuguese-version">#</a>

Inserir na documentação uma discussão com análise de projetos semelhantes e o diferencial do `dpckan` é uma boa prática pois ajuda a inserir o `dpckan` no ecossistema e o processo decisório de um novo usuário que está considerando utilizar a biblioteca.

Uma pergunta do [ROpenSci](https://github.com/ropensci/software-review/blob/master/.github/ISSUE_TEMPLATE/A-submit-software-for-review.md) que captura essa intenção é 

> Are there other R packages that accomplish the same thing? If so, how does yours differ or meet our criteria for best-in-category?

Alguns exemplos concretos de softwares com uma seção para explicação de diferenças/semelhanças

- https://github.com/rstudio/gt#how-gt-fits-in-with-other-packages-that-generate-display-tables
- https://github.com/rich-iannone/pointblank#how-pointblank-fits-in-with-other-packages-that-validate-tabular-data
- https://github.com/junegunn/fzf/wiki/Related-projects
- https://github.com/BurntSushi/ripgrep#why-shouldnt-i-use-ripgrep
- https://click.palletsprojects.com/en/8.0.x/why/

**Comment by gabrielbdornas** [comment]
@fjuniorr, acredito que esquecemos de fechar esse issue, uma vez que [arquivo](https://github.com/transparencia-mg/dpckan/blob/dev/RELATED_PROJECTS.md) foi criado durante hackathon
